name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

concurrency:
  group: terraform-google-cloud-function-iam
  cancel-in-progress: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - name: Set up Golang
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
        with:
          go-version: 1.17.6

      - name: Set up Terramate
        uses: giantswarm/install-binary-action@e97402b0aa95939ddba5b36aa77f8abc58a37fd5
        with:
          binary: terramate
          version: 0.2.2
          download_url: "https://github.com/mineiros-io/${binary}/releases/download/v${version}/terramate_${version}_linux_x86_64.tar.gz"
          tarball_binary_path: "${binary}"

      - name: Clean Up Terramate Install Artifacts
        run: rm -rf terramate

      - name: Set up Terradoc
        run: go install github.com/mineiros-io/terradoc/cmd/terradoc@af1a7b3ae3635958adf5ee2f40e0c3e70fd0803a
        env:
          GOPROXY: direct

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@17d4c9b8043b238f6f35641cdd8433da1e6f3867
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@9e653e0f7de0839150e03280e0981e0c25eaf10a
        with:
          tflint_version: v0.41.0

      - name: Setup and run pre-commit
        uses: pre-commit/action@9b88afc9cd57fd75b655d5c71bd38146d07135fe

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Check for Terraform file changes
        uses: getsentry/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
        id: changes
        with:
          filters: |
            terraform:
              - '*.tf'
              - 'test/**/*.tf'
              - 'test/**/*.go'
              - 'test/go.mod'
              - 'test/go.sum'
      - name: Set up Terraform
        if: steps.changes.outputs.terraform == 'true'
        uses: hashicorp/setup-terraform@17d4c9b8043b238f6f35641cdd8433da1e6f3867
        with:
          terraform_version: 1.2.1
          terraform_wrapper: false

      - name: Set up Golang
        if: steps.changes.outputs.terraform == 'true'
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
        with:
          go-version: 1.17.6

      - name: Run Unit Tests
        if: steps.changes.outputs.terraform == 'true'
        run: make test/unit-tests
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINEIROS_TESTING_AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MINEIROS_TESTING_AWS_ACCESS_KEY_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.MINEIROS_TESTING_GCP_SA_KEY_FILE }}
          TEST_GCP_PROJECT: ${{ secrets.MINEIROS_TESTING_GCP_PROJECT }}
          TEST_GCP_ORG_DOMAIN: ${{ secrets.MINEIROS_TESTING_GCP_ORG_DOMAIN }}
          TEST_GCP_BILLING_ACCOUNT: ${{ secrets.MINEIROS_TESTING_GCP_BILLING_ACCOUNT }}
